# This workflow will validate if the version in pyproject.toml has been upgraded to a newer version

name: Ensure Version Upgraded

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-version-upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Current branch code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: branch

      - name: Checkout target code  # Current development code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.base_ref }}
          path: ${{ github.base_ref }}

      - name: Get current version
        id: current-version
        run: |
          CURRENT_VERSION=$(grep ^version branch/pyproject.toml | sed -r 's/^version = "(.*)"(.*)/\1/g')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Get target version
        id: target-version
        run: |
          TARGET_BRANCH=${{ github.base_ref }}
          TARGET_VERSION=$(grep ^version $TARGET_BRANCH/pyproject.toml | sed -r 's/^version = "(.*)"(.*)/\1/g')
          echo "TARGET_VERSION=$TARGET_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv pip install packaging --system

      - name: Check version bump
        run: |
          python3 branch/.github/scripts/check_version_bump.py \
          ${{ steps.current-version.outputs.CURRENT_VERSION }} \
          ${{ steps.target-version.outputs.TARGET_VERSION }}
